module.exports = {
  apps: [
    {
      name:               'edge-gym-api',
      script:             './apps/api-server/dist/index.js',
      instances:          1,
      exec_mode:          'fork',
      watch:              false,
      env_production:     { NODE_ENV: 'production' },
      max_memory_restart: '350M',
      restart_delay:      4000,
      max_restarts:       10,
      min_uptime:         '5s',
      error_file:         './logs/api-err.log',
      out_file:           './logs/api-out.log',
      log_date_format:    'YYYY-MM-DD HH:mm:ss',
      exp_backoff_restart_delay: 100,
    },
    {
      name:               'edge-gym-worker',
      script:             './apps/api-server/dist/worker/index.js',
      instances:          1,
      exec_mode:          'fork',
      watch:              false,
      env_production:     { NODE_ENV: 'production' },
      max_memory_restart: '200M',
      restart_delay:      4000,
      max_restarts:       10,
      min_uptime:         '5s',
      error_file:         './logs/worker-err.log',
      out_file:           './logs/worker-out.log',
      log_date_format:    'YYYY-MM-DD HH:mm:ss',
    },

    // ── Branch edge service + hardware adapter ──────────────────────────────
    // Duplicate this block for each additional branch device.
    {
      name:               'edge-service-branch1',
      script:             './apps/edge-service/dist/index.js',
      instances:          1,
      exec_mode:          'fork',
      watch:              false,
      env_production: {
        NODE_ENV:        'production',
        EDGE_DEVICE_ID:  'branch1-edge-01',
        EDGE_BRANCH_ID:  'branch_001',
        EDGE_PORT:       '8091',
      },
      max_memory_restart: '150M',
      restart_delay:      4000,
      max_restarts:       10,
      min_uptime:         '5s',
      error_file:         './logs/edge-branch1-err.log',
      out_file:           './logs/edge-branch1-out.log',
      log_date_format:    'YYYY-MM-DD HH:mm:ss',
    },
    {
      // Hardware adapter: reads physical RFID/QR hardware → calls edge service → controls relay GPIO.
      // Must run on the branch Raspberry Pi / mini PC alongside edge-service-branch1.
      // Configure readers via readers.config.json in the working directory.
      name:               'hardware-adapter-branch1',
      script:             './apps/hardware-adapter/dist/index.js',
      cwd:                './apps/hardware-adapter',
      instances:          1,
      exec_mode:          'fork',
      watch:              false,
      env_production: {
        NODE_ENV:          'production',
        EDGE_SERVICE_URL:  'http://localhost:8091',
        HEALTH_PORT:       '8092',
        READERS_CONFIG:    './readers.config.json',
        RELAY_PULSE_MS:    '500',
        CARD_COOLDOWN_MS:  '3000',
        MOCK_MODE:         'false',
        LOG_LEVEL:         'info',
      },
      max_memory_restart: '100M',
      restart_delay:      4000,
      max_restarts:       10,
      min_uptime:         '5s',
      error_file:         './logs/hw-branch1-err.log',
      out_file:           './logs/hw-branch1-out.log',
      log_date_format:    'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
